name: Siebe
favicon: null
layout_spectrum: 0.5143262085039169
typography_spectrum: 0.54169
title: 'FILM, TRAVEL, DOCUMENTARY, STORYTELLING, SAILING'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e22f6c'
    - '#0083c5'
    - '#0000ff'
    - '#00ffff'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.8870890892576426
purpose: []
