name: Siebe
favicon: null
layout_spectrum: 0
typography_spectrum: 0.38609
title: 'FILM, TRAVEL, DOCUMENTARY, STORYTELLING, SAILING'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e22f6c'
    - '#0083c5'
    - '#0000ff'
    - '#00ffff'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
